### ISSUE TITLE
Is it available in real-time?

### ISSUE THREAD

**Issue by DavidColasRomanos** [eliasdabbas/trending-twitter#6]
Is it available in real-time? I am only able to see information about two days late. Thank you in advance.

**Comment by eliasdabbas** [comment]
Thanks David, 

The data are requested when you hit the submit button, and this is what Twitter returns.  
As far as I know it gives the currently trending topics/keywords.  

https://developer.twitter.com/en/docs/twitter-api/v1/trends/trends-for-location/api-reference/get-trends-place 

Just curious, how did you figure out that the data are late?  Can you share an example?

**Comment by DavidColasRomanos** [comment]
Thank you for your response. For example, in my case, I just updated the application at time 10:24 (CET). The time column of the table it returns has date/time: 2021-06-07T05:52:03+00:00. I can understand that the day doesn't match since we don't use the same convention, but the minutes should match...

Regards,

**Comment by eliasdabbas** [comment]
I see what you mean. 

Yes, there are two time stamps for the [trending topics](https://developer.twitter.com/en/docs/twitter-api/v1/trends/trends-for-location/api-reference/get-trends-place):

> The most up to date info available is returned on request. The `created_at` field will show when the oldest trend started trending. The `as_of` field contains the timestamp when the list of trends was created.

I chose the `created_at` timestamp, because this is probably what you want (when the oldest topics in the list were trending). You can easily add a timestamp if you want to keep track of when you requested the data. 

Source code here:

https://github.com/eliasdabbas/advertools/blob/cd87ce6cbecf231da92de0a20c927e5c349c52b0/advertools/twitter.py#L758

Hope this makes sense.

**Comment by DavidColasRomanos** [comment]
Great! It makes sense, I hadn't noticed that detail....
Thank you very much for your quick response!
Best regards
